---
discovery_task:

  description: Utilizing comprehensive inputs such as {website} and the pre-processed solutions.pdf,
    DiscoveryAgent employs the ScrapeWebsiteTool to gather crucial solution details from the website and extracts relevant data from solutions.pdf using PDFSearchTool. 
    The agent thoroughly analyzes this combined data to uncover the company's current challenges and detect any unaddressed services that Buckle Consult can potentially offer.
  expected_output: A detailed report highlighting key challenges and service gaps
    observed from {website}, along with critical solution details from solutions.pdf.
  async_execution: false
  agent: DiscoveryAgent

analysis_task:
  description: Based on the context provided by discovery_task, AnalysisAgent will
    further evaluate the data in relation to inputs such as {CRM_or_ERP} and {industry},
    validating the identified challenges and enriching insights on digital and operational
    gaps.
  expected_output: An in-depth analysis report detailing validated challenges and
    missing services, contextualized with inputs {CRM_or_ERP}, {industry}, etc.
  async_execution: false
  agent: AnalysisAgent
  context:
  - discovery_task
recommendation_task:
  description: Leveraging insights from discovery_task and analysis_task, RecommendationAgent
    will generate a detailed recommendation report. The report will outline existing
    issues, highlight missing offerings, and explain how Buckle Consult’s solutions
    can address these gaps, ensuring a natural and consultancy-like tone.
  expected_output: A comprehensive, human-written recommendation report that clearly
    demonstrates the identified problems and proposed solutions, using inputs like
    {customer_reaction_application} and {name}.
  async_execution: false
  agent: RecommendationAgent
  context:
  - discovery_task
  - analysis_task
